[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x6D7070"
blue = "0x1BA6FA"
cyan = "0x73FBF1"
green = "0xB8E466"
magenta = "0xA578EA"
red = "0xFF4352"
white = "0xFEFEF8"
yellow = "0xFFD750"

[colors.cursor]
cursor = "0xFF261E"
text = "0xEBEBEB"

[colors.normal]
black = "0x0d0d0d"
blue = "0x1BA6FA"
cyan = "0x21DEEF"
green = "0xA0E521"
magenta = "0x8763B8"
red = "0xFF301B"
white = "0xEBEBEB"
yellow = "0xFFC620"

[colors.primary]
background = "0x150b26"
foreground = "0xecc4f0"

[font]
size = 12

[font.bold]
family = "CaskaydiaCove Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "Operator Mono Lig Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Operator Mono Lig Nerd Font"
style = "Medium Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Propo"

[scrolling]
history = 50000
multiplier = 3

[terminal.shell]
program = "zsh"

[window]
opacity = 0.80
blur = true

[window.dimensions]
columns= 100
lines= 28

[window.padding]
x = 20
y = 15

[terminal]
